### PR TITLE
Add support for XML-formatted ROIs

### PR DESCRIPTION
**Pull request by emmachancellor**
The xml_to_csv() function looks for any xml files and converts them to csv inside the user-specified ROI folder. The csv files are saved in the same folder. Then, rois() has been modified to look for xml files. If they exit, it will convert the xmls to csv and add the new csv file paths to the roi list.

### CODE REVIEW

**Comment by jamesdolezal** [comment]
Nice! I would propose some small changes:

- Move Dataset.xml_to_csv() to sf.slide.utils. Its a utility function that doesn't access class variables and could have more uses outside the class (for example, by sf.WSI). Having it in a utility submodule makes it more accessible.
- Add an error check in xml_to_csv(), so an informative error is raised if an XML file is invalid 
- Instead of implicitly converting all XML files anytime Dataset.rois() is called (which could raise errors if the folders have unrelated XML files, and may be unintended), move the conversion into a new function Dataset.convert_xml_rois(). The user would then need to manually call this function, but it makes sense that they should need to. In this new function, add an error handling step that would skip XML files that raise an error during conversion.

**Comment by emmachancellor** [comment]
Sounds great, I'll make those changes!

**Comment by emmachancellor** [comment]
Hey @jamesdolezal, when you have a chance, please let me know what further modifications would be appropriate. 

Here is an overview of what has been done: 
- Moved the convert_xml_rois() to near the top of dataset.py
- Added convert_xml option to Dataset class
- Added xml_to_csv() to slide.utils.py

**Comment by jamesdolezal** [comment]
Thanks Emma - this looks great. I made some minor changes in 2c6642b, which you can review. I'll go ahead and merge this with `dev`. 

I don't have any XML-formatted ROIs handy - can you either send some my way or ensure that this works as intended?

**Pull request merged**
